version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:30"
      timezone: "UTC"
    target-branch: main
    reviewers:
      - ExpediaGroup/openworld-committers
    labels:
      - Dependabot

  - package-ecosystem: "npm"
    directory: "/core/"
    schedule:
      interval: daily
      time: "11:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: main
    reviewers:
      - ExpediaGroup/openworld-committers
    labels:
      - Dependabot

  - package-ecosystem: "npm"
    directory: "/generator/src/main/resources/dependencies/"
    schedule:
      interval: daily
      time: "11:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: main
    reviewers:
      - ExpediaGroup/openworld-committers
    labels:
      - Dependabot

  # Maintain dependencies for maven
  - package-ecosystem: maven
    directory: "/generator/"
    schedule:
      interval: daily
      time: "11:30"
      timezone: "UTC"
    open-pull-requests-limit: 10
    target-branch: main
    reviewers:
      - ExpediaGroup/openworld-committers
    labels:
      - Dependabot
