/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountTakeoverFraudDecision } from './AccountTakeoverFraudDecision'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * Response for an account transaction provided by Expedia\'s Fraud Prevention Service.
 */
@JsonObject({ constructorParams: [{}] })
export class AccountScreenResponse {
    /**
     * Unique identifier assigned to the transaction by Expedia\'s Fraud Prevention Service.
     */
    @JsonProperty({ name: 'risk_id' })
    riskId?: string
    @JsonProperty({ name: 'decision' })
    decision?: AccountTakeoverFraudDecision

    public constructor(accountScreenResponse: AccountScreenResponseProperties) {
        this.riskId = accountScreenResponse.riskId
        this.decision = accountScreenResponse.decision
    }
}

export interface AccountScreenResponseProperties {
    riskId?: string
    decision?: AccountTakeoverFraudDecision
}
