/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * Information specific to the Partner\'s device through which a transaction was made.
 */
@JsonObject({ constructorParams: [{}] })
export class AccountTakeoverDeviceDetails {
    /**
     * Source of the device_box. Default value is `TrustWidget`.
     */
    @JsonProperty({ name: 'source' })
    source?: string
    /**
     * Device related information retrieved from TrustWidget.
     */
    @JsonProperty({ name: 'device_box' })
    deviceBox: string
    /**
     * IP address of the device used for this event.
     */
    @JsonProperty({ name: 'ip_address' })
    ipAddress: string
    /**
     * The application type, operating system, software vendor, or software version of the originating request.
     */
    @JsonProperty({ name: 'user_agent' })
    userAgent: string
    /**
     * The categorized type of device used by a user. Possible values are: - `WEBSITE` - Applicable if the user initiated this event from a web browser on a desktop computer. - `PHONE_WEB` - Applicable if the user initiated this event from a web browser on a phone. - `TABLET_WEB` - Applicable if the user initiated this event from a web browser on a tablet. - `PHONE_APP` - Applicable if the user initiated this event from an app on a phone. - `TABLET_APP` - Applicable if the user initiated this event from an app on a tablet.
     */
    @JsonProperty({ name: 'type' })
    type?: AccountTakeoverDeviceDetailsTypeEnum

    public constructor(
        accountTakeoverDeviceDetails: AccountTakeoverDeviceDetailsProperties
    ) {
        this.source = accountTakeoverDeviceDetails.source
        this.deviceBox = accountTakeoverDeviceDetails.deviceBox
        this.ipAddress = accountTakeoverDeviceDetails.ipAddress
        this.userAgent = accountTakeoverDeviceDetails.userAgent
        this.type = accountTakeoverDeviceDetails.type
    }
}

export type AccountTakeoverDeviceDetailsTypeEnum =
    | 'WEBSITE'
    | 'PHONE_WEB'
    | 'TABLET_WEB'
    | 'PHONE_APP'
    | 'TABLET_APP'

export interface AccountTakeoverDeviceDetailsProperties {
    source?: string
    deviceBox: string
    ipAddress: string
    userAgent: string
    type?: AccountTakeoverDeviceDetailsTypeEnum
}
