/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * The `type` field value is used as a discriminator, with the following mapping: * `MULTI_FACTOR_AUTHENTICATION_UPDATE`: `MultiFactorAuthenticationUpdate` * `REMEDIATION_UPDATE`: `RemediationUpdate`
 */
@JsonObject({ constructorParams: [{}] })
export class AccountUpdateRequest {
    /**
     * The `risk_id` provided by Expedia\'s Fraud Prevention Service in the `AccountScreenResponse`.
     */
    @JsonProperty({ name: 'risk_id' })
    riskId: string

    public constructor(accountUpdateRequest: AccountUpdateRequestProperties) {
        this.riskId = accountUpdateRequest.riskId
    }
}

export type AccountUpdateRequestTypeEnum =
    | 'MULTI_FACTOR_AUTHENTICATION_UPDATE'
    | 'REMEDIATION_UPDATE'

export interface AccountUpdateRequestProperties {
    riskId: string
}
