/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

@JsonObject({ constructorParams: [{}] })
export class AccountTakeoverBadRequestErrorAllOfCauses {
    @JsonProperty({ name: 'code' })
    code?: AccountTakeoverBadRequestErrorAllOfCausesCodeEnum
    /**
     * A JSON Path expression indicating which field, in the request body, caused the error.
     */
    @JsonProperty({ name: 'field' })
    field?: string
    @JsonProperty({ name: 'message' })
    message?: string

    public constructor(
        accountTakeoverBadRequestErrorAllOfCauses: AccountTakeoverBadRequestErrorAllOfCausesProperties
    ) {
        this.code = accountTakeoverBadRequestErrorAllOfCauses.code
        this.field = accountTakeoverBadRequestErrorAllOfCauses.field
        this.message = accountTakeoverBadRequestErrorAllOfCauses.message
    }
}

export type AccountTakeoverBadRequestErrorAllOfCausesCodeEnum =
    | 'MISSING_MANDATORY_PARAM'
    | 'INVALID_PARAM'
    | 'INVALID_FORMAT'

export interface AccountTakeoverBadRequestErrorAllOfCausesProperties {
    code?: AccountTakeoverBadRequestErrorAllOfCausesCodeEnum
    field?: string
    message?: string
}
