/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChargebackDetail } from './ChargebackDetail'
import { ChargebackDetailMapper } from './ChargebackDetailMapper'
import { OrderPurchaseUpdateRequest } from './OrderPurchaseUpdateRequest'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'
import { OrderPurchaseUpdateRequestProperties } from './OrderPurchaseUpdateRequest'

/**
 * Feedback from EG external partners if they receive a chargeback for a false negative recommendation from Fraud Prevention system.
 */
@JsonObject({ constructorParams: [{}] })
export class ChargebackFeedback extends OrderPurchaseUpdateRequest {
    @JsonProperty({
        name: 'chargeback_detail',
        type: (property) => ChargebackDetailMapper.getType(property),
    })
    chargebackDetail?: ChargebackDetail

    @JsonProperty('type')
    readonly type = 'CHARGEBACK_FEEDBACK'

    public constructor(chargebackFeedback: ChargebackFeedbackProperties) {
        super({
            riskId: chargebackFeedback.riskId,
        })
        this.chargebackDetail = chargebackFeedback.chargebackDetail
    }
}

export interface ChargebackFeedbackProperties
    extends OrderPurchaseUpdateRequestProperties {
    chargebackDetail?: ChargebackDetail
}
