/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChallengeDetail } from './ChallengeDetail'

import { ChallengeDetailMapper } from './ChallengeDetailMapper'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * The current user session prior to this transaction, which contains details related to any challenge initiated by the Partner\'\'s system to a user before calling Expedia\'\'s Fraud Prevention Service. An example is if the Partner\'\'s system sent a Captcha challenge to the user before calling Expedia\'\'s Fraud Prevention Service.
 */
@JsonObject({ constructorParams: [{}] })
export class CurrentUserSession {
    /**
     * Unique identifier for a user\'s session on their device
     */
    @JsonProperty({ name: 'session_id' })
    sessionId?: string
    /**
     * The local date and time a user\'s session started, in ISO-8061 date and time format `yyyy-MM-ddTHH:mm:ss.SSSZ`.
     */
    @JsonProperty({ name: 'start_date_time' })
    startDateTime?: Date
    @JsonProperty({
        name: 'challenge_detail',
        type: (property) => ChallengeDetailMapper.getType(property),
    })
    challengeDetail?: ChallengeDetail

    public constructor(currentUserSession: CurrentUserSessionProperties) {
        this.sessionId = currentUserSession.sessionId
        this.startDateTime = currentUserSession.startDateTime
        this.challengeDetail = currentUserSession.challengeDetail
    }
}

export interface CurrentUserSessionProperties {
    sessionId?: string
    startDateTime?: Date
    challengeDetail?: ChallengeDetail
}
