/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './Payment'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'
import { PaymentProperties } from './Payment'

@JsonObject({ constructorParams: [{}] })
export class GiftCard extends Payment {
    /**
     * Gift card number.
     */
    @JsonProperty({ name: 'card_number' })
    cardNumber: string
    /**
     * The name of gift card holder.
     */
    @JsonProperty({ name: 'card_holder_name' })
    cardHolderName: string
    /**
     * The PIN of gift card.
     */
    @JsonProperty({ name: 'pin' })
    pin: string

    @JsonProperty('method')
    readonly method = 'GIFT_CARD'

    public constructor(giftCard: GiftCardProperties) {
        super({
            brand: giftCard.brand,
            reason: giftCard.reason,
            billingName: giftCard.billingName,
            billingAddress: giftCard.billingAddress,
            billingEmailAddress: giftCard.billingEmailAddress,
            authorizedAmount: giftCard.authorizedAmount,
            verifiedAmount: giftCard.verifiedAmount,
            threeDigitsSecureCriteria: giftCard.threeDigitsSecureCriteria,
            operations: giftCard.operations,
        })
        this.cardNumber = giftCard.cardNumber
        this.cardHolderName = giftCard.cardHolderName
        this.pin = giftCard.pin
    }
}

export interface GiftCardProperties extends PaymentProperties {
    cardNumber: string
    cardHolderName: string
    pin: string
}
