/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IssuedRefundUpdateDetails } from './IssuedRefundUpdateDetails'
import { IssuedRefundUpdateDetailsMapper } from './IssuedRefundUpdateDetailsMapper'
import { RefundUpdate } from './RefundUpdate'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'
import { RefundUpdateProperties } from './RefundUpdate'

/**
 * Data related to the issued refund that should be updated.
 */
@JsonObject({ constructorParams: [{}] })
export class IssuedRefundUpdate extends RefundUpdate {
    @JsonProperty({
        name: 'refund_details',
        type: (property) => IssuedRefundUpdateDetailsMapper.getType(property),
    })
    refundDetails?: IssuedRefundUpdateDetails

    @JsonProperty('refund_status')
    readonly refundStatus = 'ISSUED'

    public constructor(issuedRefundUpdate: IssuedRefundUpdateProperties) {
        super({
            riskId: issuedRefundUpdate.riskId,
        })
        this.refundDetails = issuedRefundUpdate.refundDetails
    }
}

export interface IssuedRefundUpdateProperties extends RefundUpdateProperties {
    refundDetails?: IssuedRefundUpdateDetails
}
