/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChargebackFeedback } from './ChargebackFeedback'
import { InsultFeedback } from './InsultFeedback'
import { OrderPurchaseUpdateRequest } from './OrderPurchaseUpdateRequest'
import { OrderUpdate } from './OrderUpdate'
import { PaymentUpdate } from './PaymentUpdate'
import { RefundUpdate } from './RefundUpdate'

export class OrderPurchaseUpdateRequestMapper {
    static subTypes = new Map<string, any>([
        ['CHARGEBACK_FEEDBACK', ChargebackFeedback],
        ['INSULT_FEEDBACK', InsultFeedback],
        ['ORDER_UPDATE', OrderUpdate],
        ['PAYMENT_UPDATE', PaymentUpdate],
        ['REFUND_UPDATE', RefundUpdate],
    ])

    static getType(property) {
        let discriminator = property.type
        if (OrderPurchaseUpdateRequestMapper.subTypes.has(discriminator)) {
            return OrderPurchaseUpdateRequestMapper.subTypes.get(discriminator)
        }
        return OrderPurchaseUpdateRequest
    }
}
