/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentStatus } from './PaymentStatus'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

@JsonObject({ constructorParams: [{}] })
export class PaymentOutcome {
    @JsonProperty({ name: 'status' })
    status?: PaymentStatus
    /**
     * A mnemonic code for the payment processing.
     */
    @JsonProperty({ name: 'code' })
    code?: string
    /**
     * A short description providing additional explanation regarding the mnemonic code.
     */
    @JsonProperty({ name: 'description' })
    description?: string

    public constructor(paymentOutcome: PaymentOutcomeProperties) {
        this.status = paymentOutcome.status
        this.code = paymentOutcome.code
        this.description = paymentOutcome.description
    }
}

export interface PaymentOutcomeProperties {
    status?: PaymentStatus
    code?: string
    description?: string
}
