/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefundUpdate } from './RefundUpdate'
import { SettledRefundUpdateDetails } from './SettledRefundUpdateDetails'
import { SettledRefundUpdateDetailsMapper } from './SettledRefundUpdateDetailsMapper'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'
import { RefundUpdateProperties } from './RefundUpdate'

/**
 * Data related to the settled refund that should be updated.
 */
@JsonObject({ constructorParams: [{}] })
export class SettledRefundUpdate extends RefundUpdate {
    @JsonProperty({
        name: 'refund_details',
        type: (property) => SettledRefundUpdateDetailsMapper.getType(property),
    })
    refundDetails?: SettledRefundUpdateDetails

    @JsonProperty('refund_status')
    readonly refundStatus = 'SETTLED'

    public constructor(settledRefundUpdate: SettledRefundUpdateProperties) {
        super({
            riskId: settledRefundUpdate.riskId,
        })
        this.refundDetails = settledRefundUpdate.refundDetails
    }
}

export interface SettledRefundUpdateProperties extends RefundUpdateProperties {
    refundDetails?: SettledRefundUpdateDetails
}
