/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * Information specific to the Partner\'s website through which a transaction was made.
 */
@JsonObject({ constructorParams: [{}] })
export class AccountTakeoverSiteInfo {
    /**
     * The locale of the website a user is accessing, which is separate from the user configured browser locale, in ISO 639-2 language code format and in ISO 3166-1 country code format.
     */
    @JsonProperty({ name: 'locale' })
    locale?: string
    /**
     * Name of the website from which the event is generated.
     */
    @JsonProperty({ name: 'name' })
    name?: string
    /**
     * The trademark brand name that is displayed to a user on the website.
     */
    @JsonProperty({ name: 'brand_name' })
    brandName: string
    /**
     * The categorized name of the page where a user initiated event is being evaluated. - `LOGIN` - Applicable if the user initiated this account event from a login web page. - `PASSWORD_RESET` - Applicable if the user initiated this account event from a password reset web page.
     */
    @JsonProperty({ name: 'placement_name' })
    placementName?: AccountTakeoverSiteInfoPlacementNameEnum

    public constructor(
        accountTakeoverSiteInfo: AccountTakeoverSiteInfoProperties,
    ) {
        this.locale = accountTakeoverSiteInfo.locale
        this.name = accountTakeoverSiteInfo.name
        this.brandName = accountTakeoverSiteInfo.brandName
        this.placementName = accountTakeoverSiteInfo.placementName
    }
}

export type AccountTakeoverSiteInfoPlacementNameEnum =
    | 'LOGIN'
    | 'PASSWORD_RESET'

export interface AccountTakeoverSiteInfoProperties {
    locale?: string
    name?: string
    brandName: string
    placementName?: AccountTakeoverSiteInfoPlacementNameEnum
}
