/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountTakeoverBadRequestErrorAllOfCauses } from './AccountTakeoverBadRequestErrorAllOfCauses'

import { AccountTakeoverBadRequestErrorAllOfCausesMapper } from './AccountTakeoverBadRequestErrorAllOfCausesMapper'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * Indicates that a bad request occurred. Typically it is an invalid parameter.
 */
@JsonObject({ constructorParams: [{}] })
export class AccountTakeoverBadRequestError {
    /**
     * Snake cased all caps error code interpreted from the HTTP status code that can programmatically be acted upon.
     */
    @JsonProperty({ name: 'code' })
    code: AccountTakeoverBadRequestErrorCodeEnum
    /**
     * A human-readable explanation of the error, specific to this error occurrence.
     */
    @JsonProperty({ name: 'message' })
    message: string
    @JsonProperty({
        name: 'causes',
        type: (property) =>
            AccountTakeoverBadRequestErrorAllOfCausesMapper.getType(property),
    })
    causes?: Array<AccountTakeoverBadRequestErrorAllOfCauses>

    public constructor(
        accountTakeoverBadRequestError: AccountTakeoverBadRequestErrorProperties,
    ) {
        this.code = accountTakeoverBadRequestError.code
        this.message = accountTakeoverBadRequestError.message
        this.causes = accountTakeoverBadRequestError.causes
    }
}

export type AccountTakeoverBadRequestErrorCodeEnum =
    | 'UNAUTHORIZED'
    | 'FORBIDDEN'
    | 'NOT_FOUND'
    | 'ACCOUNT_UPDATE_NOT_FOUND'
    | 'TOO_MANY_REQUESTS'
    | 'INTERNAL_SERVER_ERROR'
    | 'BAD_GATEWAY'
    | 'RETRYABLE_ACCOUNT_SCREEN_FAILURE'
    | 'RETRYABLE_ACCOUNT_UPDATE_FAILURE'
    | 'GATEWAY_TIMEOUT'
    | 'BAD_REQUEST'

export interface AccountTakeoverBadRequestErrorProperties {
    code: AccountTakeoverBadRequestErrorCodeEnum
    message: string
    causes?: Array<AccountTakeoverBadRequestErrorAllOfCauses>
}
