/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BadRequestErrorAllOfCauses } from './BadRequestErrorAllOfCauses'

import { BadRequestErrorAllOfCausesMapper } from './BadRequestErrorAllOfCausesMapper'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * Indicates that a bad request occurred. Typically it is an invalid parameter.
 */
@JsonObject({ constructorParams: [{}] })
export class BadRequestError {
    /**
     * Snake cased all caps error code interpreted from the HTTP status code that can programmatically be acted upon.
     */
    @JsonProperty({ name: 'code' })
    code: BadRequestErrorCodeEnum
    /**
     * A human-readable explanation of the error, specific to this error occurrence.
     */
    @JsonProperty({ name: 'message' })
    message: string
    @JsonProperty({
        name: 'causes',
        type: (property) => BadRequestErrorAllOfCausesMapper.getType(property),
    })
    causes?: Array<BadRequestErrorAllOfCauses>

    public constructor(badRequestError: BadRequestErrorProperties) {
        this.code = badRequestError.code
        this.message = badRequestError.message
        this.causes = badRequestError.causes
    }
}

export type BadRequestErrorCodeEnum =
    | 'UNAUTHORIZED'
    | 'FORBIDDEN'
    | 'NOT_FOUND'
    | 'ORDER_PURCHASE_UPDATE_NOT_FOUND'
    | 'TOO_MANY_REQUESTS'
    | 'INTERNAL_SERVER_ERROR'
    | 'BAD_GATEWAY'
    | 'RETRYABLE_ORDER_PURCHASE_SCREEN_FAILURE'
    | 'RETRYABLE_ORDER_PURCHASE_UPDATE_FAILURE'
    | 'GATEWAY_TIMEOUT'
    | 'BAD_REQUEST'

export interface BadRequestErrorProperties {
    code: BadRequestErrorCodeEnum
    message: string
    causes?: Array<BadRequestErrorAllOfCauses>
}
