/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * This field signifies the precise geographical coordinates denoting the location of the activity.
 */
@JsonObject({ constructorParams: [{}] })
export class Coordinates {
    /**
     * The latitude in degrees. It must be in the range [-90.0, +90.0].
     */
    @JsonProperty({ name: 'latitude' })
    latitude: number
    /**
     * The longitude in degrees. It must be in the range [-180.0, +180.0].
     */
    @JsonProperty({ name: 'longitude' })
    longitude: number

    public constructor(coordinates: CoordinatesProperties) {
        this.latitude = coordinates.latitude
        this.longitude = coordinates.longitude
    }
}

export interface CoordinatesProperties {
    latitude: number
    longitude: number
}
