/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

@JsonObject({ constructorParams: [{}] })
export class DeviceDetails {
    /**
     * Source of the device_box. Default value is `TrustWidget`.
     */
    @JsonProperty({ name: 'source' })
    source?: string
    /**
     * Device related information retrieved from TrustWidget.
     */
    @JsonProperty({ name: 'device_box' })
    deviceBox?: string
    /**
     * IP address of the device used for booking.
     */
    @JsonProperty({ name: 'ip_address' })
    ipAddress: string

    public constructor(deviceDetails: DeviceDetailsProperties) {
        this.source = deviceDetails.source
        this.deviceBox = deviceDetails.deviceBox
        this.ipAddress = deviceDetails.ipAddress
    }
}

export interface DeviceDetailsProperties {
    source?: string
    deviceBox?: string
    ipAddress: string
}
