/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InsultDetail } from './InsultDetail'
import { InsultDetailMapper } from './InsultDetailMapper'
import { OrderPurchaseUpdateRequest } from './OrderPurchaseUpdateRequest'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'
import { OrderPurchaseUpdateRequestProperties } from './OrderPurchaseUpdateRequest'

/**
 * Feedback from EG external partners regarding a false positive recommendation that from Fraud Prevention system gave for their customer.
 */
@JsonObject({ constructorParams: [{}] })
export class InsultFeedback extends OrderPurchaseUpdateRequest {
    @JsonProperty({
        name: 'insult_detail',
        type: (property) => InsultDetailMapper.getType(property),
    })
    insultDetail?: InsultDetail

    @JsonProperty('type')
    readonly type = 'INSULT_FEEDBACK'

    public constructor(insultFeedback: InsultFeedbackProperties) {
        super({
            riskId: insultFeedback.riskId,
        })
        this.insultDetail = insultFeedback.insultDetail
    }
}

export interface InsultFeedbackProperties
    extends OrderPurchaseUpdateRequestProperties {
    insultDetail?: InsultDetail
}
