/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payment } from './Payment'
import { Telephone } from './Telephone'

import { TelephoneMapper } from './TelephoneMapper'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'
import { PaymentProperties } from './Payment'

@JsonObject({ constructorParams: [{}] })
export class InternetBankPayment extends Payment {
    /**
     * The bank_id provided by the internet bank payment(IBP) provider (DRWP aka NetGiro) for the bank used for processing the payment.
     */
    @JsonProperty({ name: 'bank_id' })
    bankId: string
    /**
     * A code that identifies the bank branch for internet bank payment(IBP).
     */
    @JsonProperty({ name: 'bank_branch_code' })
    bankBranchCode: string
    /**
     * Telephone(s) associated with internet bank payment(IBP) provider.
     */
    @JsonProperty({
        name: 'telephones',
        type: (property) => TelephoneMapper.getType(property),
    })
    telephones: Array<Telephone>

    @JsonProperty('method')
    readonly method = 'INTERNET_BANK_PAYMENT'

    public constructor(internetBankPayment: InternetBankPaymentProperties) {
        super({
            brand: internetBankPayment.brand,
            reason: internetBankPayment.reason,
            billingName: internetBankPayment.billingName,
            billingAddress: internetBankPayment.billingAddress,
            billingEmailAddress: internetBankPayment.billingEmailAddress,
            authorizedAmount: internetBankPayment.authorizedAmount,
            verifiedAmount: internetBankPayment.verifiedAmount,
            threeDigitsSecureCriteria:
                internetBankPayment.threeDigitsSecureCriteria,
            operations: internetBankPayment.operations,
        })
        this.bankId = internetBankPayment.bankId
        this.bankBranchCode = internetBankPayment.bankBranchCode
        this.telephones = internetBankPayment.telephones
    }
}

export interface InternetBankPaymentProperties extends PaymentProperties {
    bankId: string
    bankBranchCode: string
    telephones: Array<Telephone>
}
