/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountUpdateRequest } from './AccountUpdateRequest'
import { MultiFactorAuthenticationAttempt } from './MultiFactorAuthenticationAttempt'

import { MultiFactorAuthenticationAttemptMapper } from './MultiFactorAuthenticationAttemptMapper'

import { JsonObject, JsonProperty } from 'typescript-json-serializer'
import { AccountUpdateRequestProperties } from './AccountUpdateRequest'

/**
 * Information specific to a user\'s response to a Multi-Factor Authentication initiated by the Partner\'s system as a result of a fraud recommendation.
 */
@JsonObject({ constructorParams: [{}] })
export class MultiFactorAuthenticationUpdate extends AccountUpdateRequest {
    @JsonProperty({
        name: 'multi_factor_authentication_attempts',
        type: (property) =>
            MultiFactorAuthenticationAttemptMapper.getType(property),
    })
    multiFactorAuthenticationAttempts: Array<MultiFactorAuthenticationAttempt>

    @JsonProperty('type')
    readonly type = 'MULTI_FACTOR_AUTHENTICATION_UPDATE'

    public constructor(
        multiFactorAuthenticationUpdate: MultiFactorAuthenticationUpdateProperties
    ) {
        super({
            riskId: multiFactorAuthenticationUpdate.riskId,
        })
        this.multiFactorAuthenticationAttempts =
            multiFactorAuthenticationUpdate.multiFactorAuthenticationAttempts
    }
}

export interface MultiFactorAuthenticationUpdateProperties
    extends AccountUpdateRequestProperties {
    multiFactorAuthenticationAttempts: Array<MultiFactorAuthenticationAttempt>
}
