/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * Group of attributes intended to hold information about a customer or traveler\'s name for the order.
 */
@JsonObject({ constructorParams: [{}] })
export class Name {
    /**
     * Surname, or last name, of the person.
     */
    @JsonProperty({ name: 'last_name' })
    lastName: string
    /**
     * Given, or first name, of the person.
     */
    @JsonProperty({ name: 'first_name' })
    firstName: string
    /**
     * Middle name of the person.
     */
    @JsonProperty({ name: 'middle_name' })
    middleName?: string
    /**
     * Title of the person for name (e.g. Mr., Ms. etc).
     */
    @JsonProperty({ name: 'title' })
    title?: string
    /**
     * Generational designations (e.g. Sr, Jr, III) or values that indicate the individual holds a position, educational degree, accreditation, office, or honor (e.g. PhD, CCNA, OBE).
     */
    @JsonProperty({ name: 'suffix' })
    suffix?: string

    public constructor(name: NameProperties) {
        this.lastName = name.lastName
        this.firstName = name.firstName
        this.middleName = name.middleName
        this.title = name.title
        this.suffix = name.suffix
    }
}

export interface NameProperties {
    lastName: string
    firstName: string
    middleName?: string
    title?: string
    suffix?: string
}
