/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditCard } from './CreditCard'
import { DirectDebit } from './DirectDebit'
import { GiftCard } from './GiftCard'
import { InternetBankPayment } from './InternetBankPayment'
import { PayPal } from './PayPal'
import { Payment } from './Payment'
import { Points } from './Points'

export class PaymentMapper {
    static subTypes = new Map<string, any>([
        ['CREDIT_CARD', CreditCard],
        ['DIRECT_DEBIT', DirectDebit],
        ['GIFT_CARD', GiftCard],
        ['INTERNET_BANK_PAYMENT', InternetBankPayment],
        ['PAYPAL', PayPal],
        ['POINTS', Points],
    ])

    static getType(property) {
        let discriminator = property.method
        if (PaymentMapper.subTypes.has(discriminator)) {
            return PaymentMapper.subTypes.get(discriminator)
        }
        return Payment
    }
}
