/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

/**
 * This attribute captures the name or identifier of the company responsible for operating the Rail product. It represents the specific operating entity, such as Amtrak, British Railways, or a bus company.
 */
@JsonObject({ constructorParams: [{}] })
export class RailSegmentsOperatingCompany {
    /**
     * The name used by the transportation carrier for marketing purposes in the travel segment. Example: ARX, AMTRAC, ARRIVA
     */
    @JsonProperty({ name: 'marketing_name' })
    marketingName?: string

    public constructor(
        railSegmentsOperatingCompany: RailSegmentsOperatingCompanyProperties,
    ) {
        this.marketingName = railSegmentsOperatingCompany.marketingName
    }
}

export interface RailSegmentsOperatingCompanyProperties {
    marketingName?: string
}
