/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

@JsonObject({ constructorParams: [{}] })
export class SiteInfo {
    /**
     * The alpha-3 ISO code that represents a country name.
     */
    @JsonProperty({ name: 'country_code' })
    countryCode: string
    /**
     * Identifies if an agent assisted in booking travel for the customer. `False` if the order was directly booked by customer.
     */
    @JsonProperty({ name: 'agent_assisted' })
    agentAssisted: boolean

    public constructor(siteInfo: SiteInfoProperties) {
        this.countryCode = siteInfo.countryCode
        this.agentAssisted = siteInfo.agentAssisted
    }
}

export interface SiteInfoProperties {
    countryCode: string
    agentAssisted: boolean
}
