/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { JsonObject, JsonProperty } from 'typescript-json-serializer'

@JsonObject({ constructorParams: [{}] })
export class Ticket {
    /**
     * Specifies the type of the ticket, such as ADULT, CHILD, SENIOR, STUDENT, or OTHER.
     */
    @JsonProperty({ name: 'type' })
    type: TicketTypeEnum
    /**
     * This field represents the count or number of tickets associated with the type.
     */
    @JsonProperty({ name: 'quantity' })
    quantity: number

    public constructor(ticket: TicketProperties) {
        this.type = ticket.type
        this.quantity = ticket.quantity
    }
}

export type TicketTypeEnum = 'ADULT' | 'CHILD' | 'SENIOR' | 'STUDENT' | 'OTHER'

export interface TicketProperties {
    type: TicketTypeEnum
    quantity: number
}
