/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const Authentication = {
    BEARER_EXPIRY_DATE_MARGIN: 10_000, // 10 seconds in milliseconds
    EAN: 'EAN',
    BASIC: 'Basic',
    BEARER: 'Bearer',
    AUTHORIZATION: 'Authorization',
    USERNAME: 'username',
    PASSWORD: 'password',
    CLIENT_CREDENTIALS: 'client_credentials',
    APPLICATION_FORM_URL_ENCODED: 'application/x-www-form-urlencoded',
} as const
