/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export const LoggingMessage = {
  LOGGING_INFIX: 'ExpediaGroupSDK:',
  TOKEN_RENEWAL_IN_PROCESS: 'Renewing token',
  TOKEN_RENEWAL_SUCCESSFUL: 'Token renewal successful',
  TOKEN_EXPIRED: 'Token expired or is about to expire. Request will wait until token is renewed',
  OMITTED: '<-- omitted -->'
} as const
