/*
 * Copyright (C) 2023 Expedia, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.

 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Authentication } from './Authentication'

const PCIRelatedFields: string[] = [
  'pin',
  'card_number',
  'security_code',
  'account_number',
  'card_avs_response',
  'card_cvv_response'
]

export const LogMaskingRegex = {
  AUTHORIZATION_REGEX: `(?<=(${Authentication.EAN}|${Authentication.BASIC}|${Authentication.BEARER})\\s)\\S+(?=(\\n|\\r|\\t))*(?=('|"))`,
  AUTH_USERNAME_REGEX: `(?<=${Authentication.USERNAME}:\\s('|"))\\S+(?=('|"))`,
  AUTH_PASSWORD_REGEX: `(?<=${Authentication.PASSWORD}:\\s('|"))\\S+(?=('|"))`,
  ACCESS_TOKEN_REGEX: '(?<=access_token: (\'|"))\\S+(?=(\'|"))',
  NUMBER_FIELD_REGEX: '(?<=[\'"]?number[\'"]?:\\s*[\'"])\\s*[^\\s\'"]{15,16}\\s*(?=([\'"]))',
  PCI_FIELDS_REGEX: `(?<=['"]?(${PCIRelatedFields.join('|')})['"]?:\\s*['"])\\s*[^\\s'"]+\\s*(?=(['"]))`
} as const
