name: Generate & Test SDK
on:
  pull_request:
    branches:
      - 'main'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          overwrite-settings: false
      - id: build-with-maven
        working-directory: ./generator
        run: mvn clean install -P github-generate-action-profile
      - name: Generate SDK Files
        working-directory: ./generator
        run: |
          mvn clean install
          mvn exec:java "-Dnamespace=exemplar" "-DsdkVersion=0.0.1-exemplar" "-Dspec=src/test/resources/exemplar.yaml"
      - uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: generator/target/sdk
  verify-generated-sdk:
    runs-on: ubuntu-latest
    needs: generate-sdk
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.event.pull_request.head.ref}}
      - uses: actions/download-artifact@v4
        with:
          name: sdk
          path: generator/target/sdk
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: verify generated sdk
        working-directory: ./generator/target/sdk
        run: |
          npm run prepare-sdk
          npx tsc
      - name: generate docs
        working-directory: ./generator/target/sdk
        run: |
          npm run generate-docs
      - name: update generated docs
        run: |
          rm -rf ./generator/src/test/resources/exemplar-docs/*
          cp -r ./generator/target/sdk/docs/* ./generator/src/test/resources/exemplar-docs/
          if git diff --quiet; then
            echo "No docs changes."
          else
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add ./generator/src/test/resources/exemplar-docs/
            git commit -m "chore(docs): update docs"
            git push
            echo "Docs changes committed and pushed successfully."
          fi
      - uses: actions/labeler@v5
        with:
          sync-labels: true
