name: Generate SDK - Generate
on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: actions/download-artifact@v4
        with:
          name: specs
          path: generator
      - name: generate
        working-directory: generator
        run: |
          mvn clean install
          mvn exec:java "-Dnamespace=${{ inputs.name }}" -DsdkVersion=${{ inputs.version }} "-Dspec=./specs.yaml"
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.14.1
      - name: prepare
        working-directory: generator/target/sdk
        run: |
          npm run prepare-sdk
          npm run generate-docs
          rm -r node_modules
      - uses: actions/upload-artifact@v4
        with:
          name: sdk
          path: generator/target/sdk
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: generator/target/sdk/docs
