name: Generate SDK - Main
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'SDK Name'
        required: true
      version:
        description: 'SDK Version'
        required: true
      product_endpoint:
        description: 'Endpoint to prepend specs' paths with'
        required: true
        type: string
      specs_url:
        description: 'URL to download API specs from'
        required: true
        type: string
      production_release:
        description: 'Release to Production? (yes/no)'
        required: false
        default: 'no'
jobs:
  download_specs:
    uses: ./.github/workflows/generator-download-specs.yml
    with:
      url: ${{ github.event.inputs.specs_url }}
  transform_specs:
    needs: [ download_specs ]
    uses: ./.github/workflows/generator-transform-specs.yml
    with:
      configurations: -th -te ${{ github.event.inputs.product_endpoint }} -tt ${{ github.event.inputs.name }}
  generate:
    needs: [ transform_specs ]
    uses: ./.github/workflows/generator-generate.yml
    with:
      name: ${{ github.event.inputs.name }}
      version: ${{ github.event.inputs.version }}
  publish_sources:
    needs: [ generate ]
    uses: ./.github/workflows/generator-publish-sources.yml
    with:
      name: ${{ github.event.inputs.name }}
      version: ${{ github.event.inputs.version }}
      production_release: ${{ github.event.inputs.production_release }}
