name: Generate SDK - Publish
on:
  workflow_call:
    inputs:
      production_release:
        description: 'Release to Production'
        type: boolean
        required: true
jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.publish.outputs.version }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdk
          path: generator/sdk
